name: dolo_env
dependencies:
- fastcache=1.0.2=py35_0
- llvmlite=0.8.0=py35_0
- mkl=11.3.1=0
- numba=0.23.1=np110py35_0
- numexpr=2.5=np110py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2f=0
- pandas=0.17.1=np110py35_0
- pip=8.0.2=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- readline=6.2=2
- setuptools=20.1.1=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- sympy=0.7.6.1=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
