name: dolo_env
dependencies:
- ipython
- numba
- numexpr
- numpy
- numpydoc
- pip
- pandas
- pygments
- python>=3.6
- pyyaml
- scipy
- sphinx
- sphinx_rtd_theme
- sympy
- statsmodels
- matplotlib
- xarray
# - pip:
#   - sphinx-better-theme==0.13
